---
- name: exec get.k3s.io sh
  gather_facts: true
  hosts: all

  tasks:

    - name: download get.k3s.io
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /home/k3s/get-k3s.sh
        mode: '0777'
      become: yes

    - name: exec sh
      ansible.builtin.shell: sh -s - server < /home/k3s/get-k3s.sh
      args:
        creates: /etc/systemd/system/k3s.service
      become: yes

    - name: Create .kube directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: Copy cluster config
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/k3s/.kube/config
        owner: k3s
        group: k3s
        mode: '0644'
        remote_src: yes
      become: yes

    - name: fetch config file
      fetch:
        src: /home/k3s/.kube/config
        dest: ../bh-k3s.yaml
        flat: yes
